SpareBank1/jobbsb1

gatsby-config.js
src/components/jobs.js
src/components/mjobs.js
src/pages/stilling/teamleder.md
src/pages/stilling/utvikler-boligreisen.md
src/pages/stilling/utvikler-fullstack.md
src/pages/stilling/utvikler-java.md
src/pages/stilling/utvikler-sparing.md
src/pages/stilling/utviklere.md

Lag til ny stilling, prioritet på stillingene

Utviklere stilling

---

src/components/layout.less
src/pages/stilling/teamleder.md
src/templates/pageTemplate.js

Design på pagetemplate

---

package-lock.json
src/components/layout.less
src/components/medium.js
src/components/mediumarticles.js

Diverse justeringer av layout på feeden fra Medium, iht skisser

Medium feed layout

---

src/components/header.js
src/components/layout.less

* Link til github
* Tilbakeknapp på undersider (`dark`-propen avhenger av [denne pull requesten](https://github.com/SpareBank1/designsystem/pull/621) i designsystemet)
* Smooth scroll på medium-feeden på mobil

Add link to github repo + back button in header

---

src/components/layout.less

Midlertidig fix av styling på tilbakeknapp, mens vi venter på gjenoppliving av publiseringsjobben på designsystemet.

Temporary backbutton fix

---

gatsby-node.js
src/components/header.js
src/components/layout.js
src/components/layout.less
src/pages/index.js
src/pages/markdown/designsystem.md
src/pages/markdown/fagdag.md
src/pages/markdown/fagforum.md
src/pages/markdown/hackathon.md
src/pages/markdown/markdown.md
src/pages/stilling/teamleder.md
src/pages/stilling/utvikler-boligreisen.md
src/pages/stilling/utvikler-fullstack.md
src/pages/stilling/utvikler-java.md
src/pages/stilling/utvikler-sparing.md
src/pages/stilling/utviklere.md
src/templates/openingTemplate.js

La til en egen template for stillinger, ettersom layout varierer mellom forskjellige sidetyper. Dette innebærer at markdown-filer må ha `pagetype` definert i tillegg til annen metadata.

Add separate template for openings

---

gatsby-config.js
package-lock.json
package.json

Enable google analytics

---

.travis.yml

Terminate travis if build fails

---

src/components/jobs/jobs.js

inntil vi har filter for kun dev stillinger på plass

Kommentert ut HRmanager 

---

src/pages/openings/teamleder.md

Oppdatert tekst på forespørsel

Oppdaterer teamleder-annonse

---

package-lock.json
package.json
setup-test-env.js

Oppdaterer react og testing-library

Greenkeeper/@testing library/react 9.1.0

---

src/components/layout.less
src/pages/openings/teamleder.md
src/pages/openings/utvikler-fullstack.md
src/pages/openings/utvikler-sikkerhet.md
src/pages/openings/utvikler-sparing.md
src/pages/openings/utviklere.md
src/templates/openingTemplate.js
src/templates/pageTemplate.js

Legger til nye felter for url til søknadsskjema og søknadsfrist i stillingssidene. Disse legges til som metadata i markdown-filene og vises på hver stillingsside dersom de eksisterer.

Legger til søkeknapp og utløpsdato i stillingsannonser

---

package.json

chore(package): update @testing-library/jest-dom to version 5.0.1

---

gatsby-config.js
package-lock.json
package.json

bump gatsby-source-instagram

---

src/components/jobs/jobs.js

Avdelingene Digitalbankutvikling ansatte og Design.
Cecilie skal teste ut egen publisering kalant til sb1.dev neste uke, så da slipper vi kanskje unna sånne justereinger fremover.

Lagt til design avdeling i filter

---

src/components/layout.less
src/pages/index.js

Endret "Jobber" til "Ledige stillinger". I tillegg en liten justering av bredden i feltet øverst for å få plass til den lengre teksten.

Endrer ordlyd for ledige stillinger

---

src/components/jobs/jobs.js

Ny avdeling lagt til

---

gatsby-config.js
src/components/instagram.js
src/pages/index.js

Fjerner insta til ny løsning er på plass

---

src/components/jobs/jobs.js

Ledige stillinger skal publiseres fra to nye avdelinger: 
Systemdrift Linux (21097) og Datavarehus og grunndata (21132)

Legger til Systemdrift Linux og Datavarehus og grunndata

---

.github/workflows/gh-pages.yml

Setter opp 3 automatiske bygg daglig:
* 05.30
* 12.30
* 19.30

Daglige automatiske bygg

---

src/components/jobs/jobs.js

Legger til en ny avdeling, som for øyeblikket har en arkitekt-stilling ute.

Legger til ny avdeling

---

src/pages/empati/components/card/Cards.js

Fjerner ubrukt import

---

package.json
src/pages/empati.js
src/pages/empati/components/card/Cards.js
src/pages/empati/components/card/text-card.module.less
src/pages/empati/components/card/textCards.json

WIP
Er ikke helt ferdig med denne. Ser ut som at CSSen ikke blir med. Har prøvd å fikse det.

Fikse warning message
